### ISSUE TITLE
ARCHITECT PRACTICA 3 ANTONIA MARTINEZ SANDOVAL 

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/actividad-3-practica-architect-2003lulu#1]
[Reporte de practica ARCHITECT_Antonia Mtz Sandoval.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-2003lulu/files/12581106/Reporte.de.practica.ARCHITECT_Antonia.Mtz.Sandoval.pdf)

**Comment by 27Fer12** [comment]
portada: 25 cumple con lo requerido
procedimiento: 25
figuras:25 
falto conclusion:15
puntuacion:90
calificacion:19/20

**Comment by josealfredo79** [comment]
Falta la lista de figuras...debe ir numerado las figuras...etc. por favor complementar bien el trabajo...
